name: 'Checkout Code'
description: 'Checkout the repository code with full history'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Lấy toàn bộ lịch sử commit